version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js...
      - apt-get update
      - apt-get install -y nodejs
      - echo Installing Chrome...
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt-get install -y ./google-chrome-stable_current_amd64.deb
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Building the project...
      - ng build --prod
  post_build:
    commands:
      - echo Moving appspec.yml and scripts...
      - mv appspec.yml ./dist/my-dream-app
      - mv scripts ./dist/my-dream-app
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/my-dream-app
